name: fake_firebase_remote_config
description: Fake Firebase Remote Config for use during Flutter unit & widget tests.
version: 2.0.0
homepage: https://philippbauer.me/
repository: https://github.com/CiriousJoker/fake_firebase_remote_config

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  firebase_core: ">= 2.13.0 <3.0.0"
  firebase_remote_config: ">=4.2.0 <5.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
